services:
  - type: web
    name: video-down-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    pythonVersion: 3.13.4
    envVars:
      - key: API_TOKEN
        sync: false
